---
- name: Nginx
  hosts: webservers
  become: true

  tasks:
    - name: Обновление списка пакетов
      ansible.builtin.apt:
        update_cache: yes

    - name: Установка Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Запуск сервиса Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Проверка доступности
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
        return_content: yes
      register: nginx_status

    - name: Вывод результата проверки доступности
      ansible.builtin.debug:
        var: nginx_status
