---
- name: Качаем и распаковываем Kafka
  hosts: server1
  become: true
  vars:
    kafka_version: "4.1.0"
    download_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    download_dir: "/opt/kafka"

  tasks:
    - name: Загрузки
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory

    - name: Качаем Kafka
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ download_dir }}/kafka.tgz"

    - name: Winrar
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/kafka.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
