---
- name: Установка Filebeat
  hosts: webservers
  become: yes
  tasks:
    - name: Скачать Filebeat
      ansible.builtin.get_url:
        url: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.11.0-amd64.deb"
        dest: /tmp/filebeat-8.11.0.deb
        mode: '0644'

    - name: Установить Filebeat
      ansible.builtin.apt:
        deb: /tmp/filebeat-8.11.0.deb
        state: present

    - name: Настроить filebeat.yml
      ansible.builtin.template:
        src: ../templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
      notify: Restart filebeat

    - name: Запустить и включить Filebeat
      ansible.builtin.systemd:
        name: filebeat
        state: started
        enabled: yes

  handlers:
    - name: Restart filebeat
      ansible.builtin.systemd:
        name: filebeat
        state: restarted
        enabled: yes