---
- name: Установка Kibana
  hosts: kibana
  become: yes
  tasks:
    - name: Установить Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Запустить Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Запустить контейнер Kibana
      ansible.builtin.command: |
        docker run -d \
          --name kibana \
          --restart unless-stopped \
          -p 5601:5601 \
          -e "ELASTICSEARCH_HOSTS=http://neto-elasticsearch.ru-central1.internal:9200" \
          kibana:8.11.0